import type { Metadata } from "next";
import Link from "next/link";
import { BarcodeGenerator } from "@/components/tools/BarcodeGenerator";
import { FooterCTA } from "@/components/footer-cta";

export const metadata: Metadata = {
  title:
    "Free Barcode Generator | Code 128 Barcodes for Links, SKUs & IDs | Kompi Tools",
  description:
    "Generate clean, scannable Code 128 barcodes for Kompi links, SKUs, and internal IDs. Free, no login. Perfect for packaging, labels, tickets, and inventory.",
};

const faqs = [
  {
    question: "Is the Kompi barcode generator free?",
    answer:
      "Yes. It’s completely free to use and runs in your browser. No signup or email required.",
  },
  {
    question: "What type of barcodes does this tool create?",
    answer:
      "Right now this tool generates Code 128 barcodes, which work well for URLs, SKUs, internal IDs, and short text strings.",
  },
  {
    question: "What should I put into the barcode?",
    answer:
      "We recommend using Kompi short links, SKUs, or compact internal IDs. Shorter values keep your barcodes easier to scan and nicer to print.",
  },
  {
    question: "Will this work with my existing barcode scanners?",
    answer:
      "Most handheld and POS scanners that support Code 128 will be able to read barcodes generated by this tool, as long as they’re printed clearly at a reasonable size.",
  },
  {
    question: "Does Kompi store what I type into the barcode generator?",
    answer:
      "No. The barcode is generated directly in your browser. Kompi does not store or log the text you type or paste into this tool.",
  },
  {
    question: "Can I add this barcode generator to my Kompi dashboard?",
    answer:
      "Yes. When you create a free Kompi account you can pin the barcode generator so it’s always one click away while you’re creating links and QR codes.",
  },
];

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "Kompi Barcode Generator",
  url: "https://kompi.app/tools/barcode-generator",
  applicationCategory: "UtilitiesApplication",
  description:
    "Generate clean, scannable Code 128 barcodes for Kompi links, SKUs, and internal IDs.",
  operatingSystem: "Any",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
};

export default function PublicBarcodeGeneratorPage() {
  return (
    <main className="min-h-screen bg-[#F7F7F3] text-foreground">
      {/* HERO */}
      <section className="relative overflow-hidden">
        <div className="pointer-events-none absolute inset-x-0 top-[-7rem] -z-10 transform-gpu blur-3xl">
          <div className="mx-auto h-64 max-w-3xl bg-gradient-to-r from-[#A3CF3D] via-[#9BDFD1] to-[#4B9FFF] opacity-60" />
        </div>

        <div className="mx-auto flex min-h-[90vh] max-w-5xl flex-col items-center justify-center px-4 text-center sm:px-6 lg:px-8">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full bg-white px-4 py-1.5 text-xs font-medium text-[#1E2330] ring-1 ring-[#D1FAE5]">
            <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-[#1E2330] text-[10px] font-semibold text-white">
              K
            </span>
            <span>Kompi Tools · Barcode generator</span>
          </div>

          <div className="space-y-7">
            <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl md:text-5xl">
              Turn{" "}
              <span className="bg-gradient-to-r from-[#A3CF3D] to-[#4B9FFF] bg-clip-text text-transparent">
                links, SKUs, and IDs
              </span>{" "}
              into barcodes your scanners actually like.
            </h1>

            <p className="mx-auto max-w-3xl text-base leading-relaxed text-[#4B5563] sm:text-lg">
              Paste a Kompi short link, SKU, or internal ID. Kompi instantly
              generates a clean Code 128 barcode you can download and drop into
              packaging, labels, tickets, or internal docs.
            </p>

            <div className="mt-4 flex flex-wrap items-center justify-center gap-3">
              <a
                href="#barcode-generator-tool"
                className="inline-flex items-center justify-center rounded-full bg-[#1E2330] px-7 py-3 text-sm font-medium text-[#F7F7F3] shadow-md shadow-[#1E2330]/25 transition hover:bg-black"
              >
                Generate barcodes
              </a>
              <Link
                href="/signup"
                className="inline-flex items-center justify-center rounded-full border border-[#1E2330] bg-[#FFFFFF] px-7 py-3 text-sm font-medium text-[#1E2330] shadow-sm hover:bg-[#F7F7F3]"
              >
                Add to my Kompi dashboard
              </Link>
            </div>

            <div className="mt-6 flex flex-wrap items-center justify-center gap-4 text-xs font-medium text-[#6B7280] sm:text-sm">
              <div className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-1 ring-1 ring-[#D1FAE5]">
                <span className="h-1.5 w-1.5 rounded-full bg-[#22C55E]" />
                Runs 100% in your browser
              </div>
              <span>• No login or email required</span>
              <span>• Code 128 format for scanners & POS</span>
            </div>
          </div>
        </div>
      </section>

      {/* TOOL SECTION */}
      <section
        id="barcode-generator-tool"
        className="-mt-10 bg-[#F7F7F3] px-4 pb-20 pt-0 sm:px-6 lg:px-8"
      >
        <div className="mx-auto max-w-3xl rounded-[2rem] border border-[#A3CF3D] bg-[#FFFFFF] p-[1px]">
          <div className="rounded-[1.9rem] bg-[#FFFFFF] px-4 py-5 sm:px-6 sm:py-7 lg:px-8 lg:py-8">
            <BarcodeGenerator />
          </div>
        </div>
      </section>

      {/* PLAN-STYLE CARDS */}
      <section className="bg-[#FFFFFF] px-4 py-20 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-5xl space-y-12">
          <div className="space-y-4 text-center">
            <h2 className="text-xs font-semibold uppercase tracking-[0.3em] text-[#1E2330] sm:text-sm">
              BARCODES FOR ANYTHING THAT GETS SCANNED
            </h2>
            <p className="text-2xl font-semibold tracking-tight sm:text-3xl md:text-4xl">
              One barcode generator, three very normal use cases.
            </p>
            <p className="mx-auto max-w-2xl text-sm leading-relaxed text-[#4B5563] sm:text-base">
              Whether you&apos;re printing product labels, handing out event
              passes, or tagging internal equipment — Kompi gives you barcodes
              that match your links and analytics, not random generators in a
              new tab.
            </p>
          </div>

          <div className="grid gap-6 md:grid-cols-3">
            {/* Card 1 */}
            <div className="flex flex-col justify-between rounded-3xl bg-[#F7F7F3] p-7 ring-1 ring-[#E5E7EB]">
              <div className="space-y-4">
                <p className="text-xs font-semibold uppercase tracking-wide text-[#6B7280]">
                  PACKAGING & LABELS
                </p>
                <h3 className="text-xl font-semibold text-[#1E2330] sm:text-2xl">
                  For products & samples
                </h3>
                <p className="text-sm text-[#4B5563] sm:text-base">
                  Print barcodes that lead straight to Kompi links for specs,
                  how-to videos, or re-order pages.
                </p>
                <ul className="mt-2 space-y-1.5 text-sm text-[#374151]">
                  <li>• Link packaging to a clean landing page</li>
                  <li>• Reuse the same short link across prints</li>
                  <li>• Track scans with Kompi analytics</li>
                </ul>
              </div>
              <button className="mt-7 inline-flex w-full items-center justify-center rounded-full border border-[#1E2330] bg-white px-4 py-2.5 text-xs font-medium text-[#1E2330] hover:bg-[#F7F7F3]">
                Create barcodes for packaging
              </button>
            </div>

            {/* Card 2 – highlighted */}
            <div className="flex flex-col justify-between rounded-3xl bg-[#DCFCE7] p-7 ring-2 ring-[#1E2330]">
              <div className="space-y-4">
                <div className="inline-flex items-center gap-2 rounded-full bg-[#1E2330] px-3 py-1 text-[11px] font-semibold text-[#F7F7F3]">
                  <span className="h-1.5 w-1.5 rounded-full bg-[#22C55E]" />
                  Recommended
                </div>
                <h3 className="text-xl font-semibold text-[#1E2330] sm:text-2xl">
                  For events & passes
                </h3>
                <p className="text-sm text-[#111827] sm:text-base">
                  Generate scannable barcodes for tickets, attendee badges, or
                  on-site offers that all route through your Kompi links.
                </p>
                <ul className="mt-2 space-y-1.5 text-sm text-[#111827]">
                  <li>• Keep check-in flows simple for staff</li>
                  <li>• Point every scan to a tracked URL</li>
                  <li>• Swap destinations without reprinting</li>
                </ul>
              </div>
              <button className="mt-7 inline-flex w-full items-center justify-center rounded-full bg-[#1E2330] px-4 py-2.5 text-xs font-semibold text-[#F7F7F3] hover:bg-black">
                Generate barcodes for tickets
              </button>
            </div>

            {/* Card 3 */}
            <div className="flex flex-col justify-between rounded-3xl bg-[#E0F2FE] p-7 ring-1 ring-[#BFDBFE]">
              <div className="space-y-4">
                <p className="text-xs font-semibold uppercase tracking-wide text-[#1D4ED8]">
                  INTERNAL & OPS
                </p>
                <h3 className="text-xl font-semibold text-[#1E2330] sm:text-2xl">
                  For equipment & inventory
                </h3>
                <p className="text-sm text-[#4B5563] sm:text-base">
                  Label laptops, shelves, or internal gear with IDs that open
                  a Kompi link to the right doc or system.
                </p>
                <ul className="mt-2 space-y-1.5 text-sm text-[#374151]">
                  <li>• Use compact IDs or short URLs</li>
                  <li>• Keep everything readable by one scanner</li>
                  <li>• Update destinations without new stickers</li>
                </ul>
              </div>
              <button className="mt-7 inline-flex w-full items-center justify-center rounded-full border border-[#1D4ED8] bg-[#1D4ED8] px-4 py-2.5 text-xs font-semibold text-white hover:bg-[#1E40AF]">
                Label internal assets
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* BRIGHT STRIP */}
      <section className="bg-[#F7F7F3] px-4 py-16 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-5xl">
          <div className="overflow-hidden rounded-[999px] bg-[#1E2330] px-8 py-10 text-center text-[#E5F9F0] sm:px-12">
            <h2 className="text-xl font-semibold sm:text-2xl md:text-3xl">
              Your barcodes shouldn&apos;t live in a totally separate system.
            </h2>
            <p className="mx-auto mt-3 max-w-2xl text-sm sm:text-base">
              Use Kompi to generate barcodes that stay connected to your links,
              QR codes, and analytics. Change where they point without changing
              the print.
            </p>
            <div className="mt-6 flex flex-wrap items-center justify-center gap-3">
              <a
                href="#barcode-generator-tool"
                className="inline-flex items-center justify-center rounded-full bg-[#F5FDF5] px-6 py-2.5 text-xs font-semibold text-[#111827] hover:bg-white"
              >
                Generate barcodes
              </a>
              <Link
                href="/signup"
                className="inline-flex items-center justify-center rounded-full border border-[#E5F9F0] bg-transparent px-6 py-2.5 text-xs font-medium text-[#E5F9F0] hover:bg-[#E5F9F0]/10"
              >
                Create free Kompi account
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* FEATURE PANELS */}
      <section className="bg-[#FFFFFF] px-4 py-20 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-5xl space-y-12">
          <h2 className="text-center text-2xl font-semibold tracking-tight sm:text-3xl md:text-4xl">
            Barcodes that match the rest of your Kompi stack.
          </h2>

          {/* Panel 1 */}
          <div className="grid gap-10 rounded-3xl bg-[#E5ECFF] p-10 sm:grid-cols-2 sm:p-16">
            <div className="space-y-5">
              <p className="text-xs font-semibold uppercase tracking-[0.25em] text-[#1E2330] sm:text-sm">
                FOR FOUNDERS & SMALL TEAMS
              </p>
              <h3 className="text-2xl font-semibold text-[#1E2330] sm:text-3xl">
                Link packaging, QR codes, and barcodes to the same place.
              </h3>
              <p className="text-sm leading-relaxed text-[#374151] sm:text-base">
                Use Kompi to keep QR codes, barcodes, and links all pointing to
                the same destination. When things change, you update it once in
                Kompi instead of reprinting everything.
              </p>
            </div>
            <div className="flex items-center justify-center">
              <div className="h-56 w-56 rounded-[2rem] bg-[#F7F7F3] sm:h-80 sm:w-80">
                <div className="flex h-full w-full items-center justify-center px-6 text-center text-xs text-[#6B7280]">
                  One short link behind your QR codes, barcodes, and “scan me”
                  moments — all managed inside Kompi.
                </div>
              </div>
            </div>
          </div>

          {/* Panel 2 */}
          <div className="grid gap-10 rounded-3xl bg-[#DCFCE7] p-10 sm:grid-cols-2 sm:p-16">
            <div className="order-2 flex items-center justify-center sm:order-1">
              <div className="h-56 w-56 rounded-[2rem] bg-[#F7F7F3] sm:h-80 sm:w-80">
                <div className="flex h-full w-full items-center justify-center px-6 text-center text-xs text-[#4B5563]">
                  Generate labels live while you&apos;re mapping flows and
                  offers with your team.
                </div>
              </div>
            </div>
            <div className="order-1 space-y-5 sm:order-2">
              <p className="text-xs font-semibold uppercase tracking-[0.25em] text-[#166534] sm:text-sm">
                FOR OPS & ENABLEMENT
              </p>
              <h3 className="text-2xl font-semibold text-[#052e16] sm:text-3xl">
                Make “scan this” a predictable part of your process.
              </h3>
              <p className="text-sm leading-relaxed text-[#111827] sm:text-base">
                Use Kompi to spin up barcodes during handover docs, process
                reviews, or launch checklists — not as an afterthought at the
                printer.
              </p>
            </div>
          </div>

          {/* Panel 3 */}
          <div className="grid gap-10 rounded-3xl bg-[#111827] p-10 sm:grid-cols-2 sm:p-16">
            <div className="space-y-5">
              <p className="text-xs font-semibold uppercase tracking-[0.25em] text-[#93C5FD] sm:text-sm">
                FOR ANYONE WHO HATES FRAGILE LINKS
              </p>
              <h3 className="text-2xl font-semibold text-[#F9FAFB] sm:text-3xl">
                Update the destination, not the barcode.
              </h3>
              <p className="text-sm leading-relaxed text-[#E5E7EB] sm:text-base">
                Because the barcode points to a Kompi short link, you can change
                what loads after the scan without changing your printed labels
                or tickets. No more “this URL is out of date” moments.
              </p>
            </div>
            <div className="flex items-center justify-center">
              <div className="h-56 w-56 rounded-[2rem] bg-[#020617] sm:h-80 sm:w-80">
                <div className="flex h-full w-full items-center justify-center px-6 text-center text-xs text-[#E5E7EB]">
                  Built to keep your offline touchpoints flexible instead of
                  hard-coded into packaging and print.
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* TESTIMONIAL ROW */}
      <section className="bg-[#F7F7F3] px-4 py-20 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-5xl space-y-10">
          <div className="space-y-3 text-center">
            <h2 className="text-xs font-semibold uppercase tracking-[0.3em] text-[#6B7280] sm:text-sm">
              LESS FRICTION, MORE SCANS
            </h2>
            <p className="text-2xl font-semibold tracking-tight sm:text-3xl">
              Less “which generator was that?”, more “scan, done”.
            </p>
          </div>

          <div className="grid gap-4 md:grid-cols-3">
            <div className="rounded-3xl bg-[#FFFFFF] p-5 ring-1 ring-[#E5E7EB]">
              <p className="mb-2 text-xs text-[#FBBF24]">★★★★★</p>
              <p className="text-sm font-semibold text-[#1E2330]">
                “Everything runs through Kompi now”
              </p>
              <p className="mt-2 text-xs text-[#4B5563]">
                “Nice to have barcodes, QR codes, and links in one place
                instead of three random tools.”
              </p>
            </div>
            <div className="rounded-3xl bg-[#FFFFFF] p-5 ring-1 ring-[#E5E7EB]">
              <p className="mb-2 text-xs text-[#FBBF24]">★★★★★</p>
              <p className="text-sm font-semibold text-[#1E2330]">
                “Works with our existing scanners”
              </p>
              <p className="mt-2 text-xs text-[#4B5563]">
                “We dropped the barcodes into our shelf labels and our Code 128
                scanners picked them up straight away.”
              </p>
            </div>
            <div className="rounded-3xl bg-[#FFFFFF] p-5 ring-1 ring-[#E5E7EB]">
              <p className="mb-2 text-xs text-[#FBBF24]">★★★★★</p>
              <p className="text-sm font-semibold text-[#1E2330]">
                “No more dead URLs on packaging”
              </p>
              <p className="mt-2 text-xs text-[#4B5563]">
                “If something changes, we update the Kompi link and the barcode
                just keeps working. Way less painful than reprinting.”
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="bg-[#FFFFFF] px-4 pb-20 pt-16 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-5xl gap-14 space-y-10 lg:grid lg:grid-cols-[minmax(0,1.1fr)_minmax(0,1.3fr)] lg:space-y-0">
          <div className="space-y-3">
            <h2 className="text-2xl font-semibold tracking-tight sm:text-3xl">
              Questions about the Kompi barcode generator?
            </h2>
            <p className="text-sm leading-relaxed text-[#4B5563] sm:text-base">
              Here&apos;s what people usually ask before they start putting
              barcodes on packaging, tickets, or internal gear.
            </p>
          </div>

          <div className="space-y-4">
            {faqs.map((item) => (
              <div
                key={item.question}
                className="rounded-2xl border border-[#E5E7EB] bg-[#F7F7F3] p-5 text-sm"
              >
                <h3 className="mb-1 text-sm font-medium text-[#1E2330] sm:text-base">
                  {item.question}
                </h3>
                <p className="text-sm leading-relaxed text-[#4B5563]">
                  {item.answer}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Global footer CTA */}
      <FooterCTA />

      {/* JSON-LD schema markup */}
      <script
        type="application/ld+json"
         
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
    </main>
  );
}
