// src/components/k-cards/kcard-theme-presets.ts

export type KCardFontToken = "system" | "serif" | "display";
export type KCardButtonStyle = "solid" | "glass" | "outline";
export type KCardButtonShadow = "none" | "soft" | "hard" | "3d";

export type KCardThemeState = {
  id: string;
  name: string;

  wallpaper: string;
  pageBackground: string;

  titleColor: string;
  pageTextColor: string;

  buttonColor: string;
  buttonTextColor: string;
  buttonRadius: number;
  buttonStyle: KCardButtonStyle;
  buttonShadow: KCardButtonShadow;

  titleFont: KCardFontToken;
  pageFont: KCardFontToken;

  curated?: boolean;
};

// Full presets
export const KCARD_THEME_PRESETS: KCardThemeState[] = [
  // ---------- Customizable ----------
  {
    id: "custom",
    name: "Custom",
    wallpaper: "linear-gradient(135deg,#020617,#020617,#020617)",
    pageBackground: "#020617",
    titleColor: "#f9fafb",
    pageTextColor: "#e5e7eb",
    buttonColor: "#020617",
    buttonTextColor: "#f9fafb",
    buttonRadius: 24,
    buttonStyle: "solid",
    buttonShadow: "soft",
    titleFont: "display",
    pageFont: "system",
  },
  {
    id: "agate",
    name: "Agate",
    wallpaper: "linear-gradient(135deg,#0f766e,#22c55e,#a3e635)",
    pageBackground: "#022c22",
    titleColor: "#ecfdf5",
    pageTextColor: "#bbf7d0",
    buttonColor: "#22c55e",
    buttonTextColor: "#022c22",
    buttonRadius: 24,
    buttonStyle: "solid",
    buttonShadow: "soft",
    titleFont: "display",
    pageFont: "system",
  },
  {
    id: "air",
    name: "Air",
    wallpaper: "linear-gradient(135deg,#e0f2fe,#e5e7eb,#f9fafb)",
    pageBackground: "#ffffff",
    titleColor: "#020617",
    pageTextColor: "#4b5563",
    buttonColor: "#020617",
    buttonTextColor: "#f9fafb",
    buttonRadius: 18,
    buttonStyle: "solid",
    buttonShadow: "soft",
    titleFont: "system",
    pageFont: "system",
  },
  {
    id: "astrid",
    name: "Astrid",
    wallpaper: "linear-gradient(135deg,#020617,#1e293b,#0f172a)",
    pageBackground: "#020617",
    titleColor: "#f9fafb",
    pageTextColor: "#e5e7eb",
    buttonColor: "#020617",
    buttonTextColor: "#f9fafb",
    buttonRadius: 24,
    buttonStyle: "glass",
    buttonShadow: "soft",
    titleFont: "display",
    pageFont: "system",
  },
  {
    id: "aura",
    name: "Aura",
    wallpaper: "linear-gradient(135deg,#f97316,#ec4899,#6366f1)",
    pageBackground: "#020617",
    titleColor: "#fefce8",
    pageTextColor: "#fee2e2",
    buttonColor: "#020617",
    buttonTextColor: "#fefce8",
    buttonRadius: 999,
    buttonStyle: "glass",
    buttonShadow: "soft",
    titleFont: "display",
    pageFont: "system",
  },
  {
    id: "bliss",
    name: "Bliss",
    wallpaper: "linear-gradient(135deg,#e5e7eb,#f9fafb,#d1fae5)",
    pageBackground: "#f9fafb",
    titleColor: "#111827",
    pageTextColor: "#4b5563",
    buttonColor: "#111827",
    buttonTextColor: "#f9fafb",
    buttonRadius: 18,
    buttonStyle: "solid",
    buttonShadow: "soft",
    titleFont: "system",
    pageFont: "system",
  },
  {
    id: "blocks",
    name: "Blocks",
    wallpaper: "linear-gradient(135deg,#4c1d95,#7c3aed,#ec4899)",
    pageBackground: "#020617",
    titleColor: "#f9fafb",
    pageTextColor: "#e5e7eb",
    buttonColor: "#4c1d95",
    buttonTextColor: "#f9fafb",
    buttonRadius: 16,
    buttonStyle: "solid",
    buttonShadow: "hard",
    titleFont: "display",
    pageFont: "system",
  },
  {
    id: "bloom",
    name: "Bloom",
    wallpaper: "linear-gradient(135deg,#ef4444,#f97316,#fb7185)",
    pageBackground: "#111827",
    titleColor: "#fef2f2",
    pageTextColor: "#fee2e2",
    buttonColor: "#f97316",
    buttonTextColor: "#111827",
    buttonRadius: 24,
    buttonStyle: "solid",
    buttonShadow: "soft",
    titleFont: "display",
    pageFont: "system",
  },
  {
    id: "breeze",
    name: "Breeze",
    wallpaper: "linear-gradient(135deg,#f9a8d4,#fdf2f8,#e0f2fe)",
    pageBackground: "#fdf2f8",
    titleColor: "#0f172a",
    pageTextColor: "#4b5563",
    buttonColor: "#0f172a",
    buttonTextColor: "#f9fafb",
    buttonRadius: 999,
    buttonStyle: "solid",
    buttonShadow: "soft",
    titleFont: "serif",
    pageFont: "system",
  },

  // ---------- Curated ----------
  {
    id: "grid",
    name: "Grid",
    wallpaper: "linear-gradient(135deg,#bef264,#4ade80,#22c55e)",
    pageBackground: "#022c22",
    titleColor: "#ecfdf5",
    pageTextColor: "#bbf7d0",
    buttonColor: "#16a34a",
    buttonTextColor: "#022c22",
    buttonRadius: 24,
    buttonStyle: "solid",
    buttonShadow: "soft",
    titleFont: "display",
    pageFont: "system",
    curated: true,
  },
  {
    id: "groove",
    name: "Groove",
    wallpaper:
      "radial-gradient(circle at 0 0,#fb7185,#4f46e5,#0ea5e9)",
    pageBackground: "#020617",
    titleColor: "#f9fafb",
    pageTextColor: "#e5e7eb",
    buttonColor: "#020617",
    buttonTextColor: "#f9fafb",
    buttonRadius: 24,
    buttonStyle: "glass",
    buttonShadow: "soft",
    titleFont: "display",
    pageFont: "system",
    curated: true,
  },
  {
    id: "haven",
    name: "Haven",
    wallpaper: "linear-gradient(135deg,#facc15,#fed7aa,#bbf7d0)",
    pageBackground: "#292524",
    titleColor: "#fef3c7",
    pageTextColor: "#f5f5f4",
    buttonColor: "#1c1917",
    buttonTextColor: "#fef3c7",
    buttonRadius: 22,
    buttonStyle: "solid",
    buttonShadow: "soft",
    titleFont: "serif",
    pageFont: "system",
    curated: true,
  },
  {
    id: "lake",
    name: "Lake",
    wallpaper: "linear-gradient(135deg,#0f172a,#1d4ed8,#38bdf8)",
    pageBackground: "#020617",
    titleColor: "#e0f2fe",
    pageTextColor: "#bfdbfe",
    buttonColor: "#1d4ed8",
    buttonTextColor: "#eff6ff",
    buttonRadius: 20,
    buttonStyle: "solid",
    buttonShadow: "hard",
    titleFont: "display",
    pageFont: "system",
    curated: true,
  },
  {
    id: "mineral",
    name: "Mineral",
    wallpaper: "linear-gradient(135deg,#fefce8,#f5f5f4,#e5e7eb)",
    pageBackground: "#fafaf9",
    titleColor: "#111827",
    pageTextColor: "#4b5563",
    buttonColor: "#111827",
    buttonTextColor: "#f9fafb",
    buttonRadius: 18,
    buttonStyle: "outline",
    buttonShadow: "none",
    titleFont: "serif",
    pageFont: "system",
    curated: true,
  },
  {
    id: "rise",
    name: "Rise",
    wallpaper: "linear-gradient(135deg,#f97316,#fde68a,#22c55e)",
    pageBackground: "#0f172a",
    titleColor: "#fefce8",
    pageTextColor: "#fee2e2",
    buttonColor: "#f97316",
    buttonTextColor: "#0f172a",
    buttonRadius: 26,
    buttonStyle: "solid",
    buttonShadow: "soft",
    titleFont: "display",
    pageFont: "system",
    curated: true,
  },
  {
    id: "sweat",
    name: "Sweat",
    wallpaper: "linear-gradient(135deg,#0ea5e9,#6366f1,#f97316)",
    pageBackground: "#020617",
    titleColor: "#f9fafb",
    pageTextColor: "#e5e7eb",
    buttonColor: "#0ea5e9",
    buttonTextColor: "#0f172a",
    buttonRadius: 24,
    buttonStyle: "solid",
    buttonShadow: "hard",
    titleFont: "display",
    pageFont: "system",
    curated: true,
  },
  {
    id: "vox",
    name: "Vox",
    wallpaper: "linear-gradient(135deg,#ef4444,#b91c1c,#0f172a)",
    pageBackground: "#020617",
    titleColor: "#fee2e2",
    pageTextColor: "#fecaca",
    buttonColor: "#b91c1c",
    buttonTextColor: "#fef2f2",
    buttonRadius: 20,
    buttonStyle: "solid",
    buttonShadow: "hard",
    titleFont: "display",
    pageFont: "system",
    curated: true,
  },
];

export const DEFAULT_KCARD_THEME: KCardThemeState =
  KCARD_THEME_PRESETS.find((t) => t.id === "custom") ?? KCARD_THEME_PRESETS[0];
