// src/app/(seo)/whatsapp-link-generator/page.tsx

import type { Metadata } from "next";
import Script from "next/script";
import Link from "next/link";
import { Navbar } from "@/components/navbar";
import { FooterCTA } from "@/components/footer-cta";
import ContactLinkGenerator from "@/components/tools/ContactLinkGenerator";

const DOMAIN = "https://kompi.app";
const SEO_VIDEO_SRC = "/seo/whatsapp-link-generator.mp4";
const SEO_VIDEO_ABS = `${DOMAIN}${SEO_VIDEO_SRC}`;
const SEO_THUMBNAIL_ABS = `${DOMAIN}/kompi-platform.png`;

type FaqItem = {
  question: string;
  answer: string;
};

type HowToStep = {
  position: number;
  name: string;
  text: string;
};

const faqs: FaqItem[] = [
  {
    question: "What is a WhatsApp link generator?",
    answer:
      "A WhatsApp link generator lets you create click-to-chat links like wa.me or api.whatsapp.com URLs that open a chat with a specific phone number. Kompi’s WhatsApp link generator also lets you pre-fill a message, add UTM parameters for tracking and save links inside your Kompi workspace.",
  },
  {
    question: "Is the Kompi WhatsApp link generator free?",
    answer:
      "Yes. You can use Kompi’s WhatsApp link generator online for free to create unlimited click-to-chat links. When you’re ready for more advanced workflows, you can upgrade to a paid workspace for link tracking, QR codes, menus and more.",
  },
  {
    question: "Can I pre-fill the message text in a WhatsApp link?",
    answer:
      "Definitely. Just type the message you want in the generator and Kompi will automatically URL-encode it. When people tap your link or scan your QR, WhatsApp opens with that message ready to send.",
  },
  {
    question: "Can I use the generator for WhatsApp Business?",
    answer:
      "Yes. WhatsApp Business uses the same click-to-chat format as regular WhatsApp. As long as the number is registered with WhatsApp, the links generated by Kompi will work for both personal and Business accounts.",
  },
  {
    question: "Can I create WhatsApp links for groups?",
    answer:
      "If you have an invite link for a WhatsApp group, you can shorten and track it using Kompi Links. The WhatsApp link generator itself is focused on click-to-chat links that open a conversation with a specific number and pre-filled message.",
  },
  {
    question: "How do I track clicks on my WhatsApp links?",
    answer:
      "Create your click-to-chat URL with the generator, then wrap it in a Kompi short link with UTM parameters from the UTM Builder. That way you can see which buttons, bios, QR codes or campaigns drive the most WhatsApp conversations.",
  },
  {
    question: "Should I use country codes in WhatsApp links?",
    answer:
      "Yes. Always include your full international phone number without leading zeros or special characters. For example, a UK number should start with 44 and a US number should start with 1. Kompi’s WhatsApp link generator makes it clear how to format this correctly.",
  },
  {
    question: "Can I turn a WhatsApp link into a QR code?",
    answer:
      "Absolutely. After generating your WhatsApp link, you can paste it into Kompi’s QR code generator to create a scannable QR. It works great on menus, flyers, packaging, business cards and in-store signage.",
  },
  {
    question: "Where can I safely use WhatsApp links?",
    answer:
      "You can add WhatsApp links to websites, link-in-bio pages, emails, QR codes, social bios, ads and more. Just remember that anyone who taps the link can start a chat with that number, so use a number that’s ready for customer messages.",
  },
];

const howToSteps: HowToStep[] = [
  {
    position: 1,
    name: "Add your WhatsApp number",
    text: "Enter your full WhatsApp phone number with country code, without spaces or special characters, so WhatsApp knows exactly who to open a chat with.",
  },
  {
    position: 2,
    name: "Write a pre-filled message (optional)",
    text: "Type the message you’d like to appear by default when someone taps your WhatsApp link, such as a sales inquiry, booking request or support question.",
  },
  {
    position: 3,
    name: "Choose link style & tracking",
    text: "Generate a raw WhatsApp URL or wrap it with a branded Kompi short link and UTM parameters so you can track exactly where clicks are coming from.",
  },
  {
    position: 4,
    name: "Use your link or QR code everywhere",
    text: "Copy the link into buttons, bios or ads, or turn it into a QR code with Kompi so customers can start a WhatsApp conversation from print and in-store signage.",
  },
];

export const metadata: Metadata = {
  title:
    "Free WhatsApp Link Generator | Create Click-to-Chat Links & QR Codes | Kompi",
  description:
    "Create WhatsApp click-to-chat links in seconds. Use Kompi’s free WhatsApp link generator to add pre-filled messages, tracking and QR codes for sites, bios, menus and campaigns.",
  keywords: [
    "whatsapp link generator",
    "whatsapp url generator",
    "create whatsapp link",
    "click to chat whatsapp",
    "whatsapp chat link",
    "whatsapp api link generator",
    "whatsapp business link",
    "whatsapp link with message",
    "whatsapp link maker online",
    "whatsapp link for website",
    "whatsapp link for instagram bio",
    "whatsapp qr code generator",
    "free whatsapp link generator",
    "whatsapp wa.me link",
    "api.whatsapp.com send",
    "kompi whatsapp link tool",
  ],
  alternates: {
    canonical: "/whatsapp-link-generator",
  },
  openGraph: {
    title:
      "Free WhatsApp Link Generator | Create Click-to-Chat Links & QR Codes",
    description:
      "Build WhatsApp click-to-chat links with pre-filled messages and tracking, then turn them into QR codes and smart links with Kompi.",
    url: `${DOMAIN}/whatsapp-link-generator`,
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title:
      "Free WhatsApp Link Generator | Create Click-to-Chat Links & QR Codes",
    description:
      "Generate WhatsApp links with pre-filled messages, UTM tracking and QR codes using Kompi’s free WhatsApp link generator.",
  },
  robots: {
    index: true,
    follow: true,
  },
};

/* -------------------------------------------------------------------------- */
/*  HERO SECTION                                                              */
/* -------------------------------------------------------------------------- */

function WhatsappHeroSection() {
  return (
    <section className="relative overflow-hidden">
      <div className="pointer-events-none absolute inset-x-0 -top-24 -z-10 transform-gpu blur-3xl">
        <div className="mx-auto h-48 max-w-3xl bg-gradient-to-r from-[#22c55e]/25 via-[#16a34a]/10 to-[#0f172a]/20 opacity-80" />
      </div>

      <div className="mx-auto flex max-w-5xl flex-col items-center justify-center px-4 pb-10 pt-12 text-center sm:px-6 md:pb-14 md:pt-16">
        <div className="mb-6 inline-flex items-center gap-2 rounded-full bg-white px-4 py-1.5 text-xs font-medium text-[#022c22] shadow-sm ring-1 ring-emerald-100">
          <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-[#022c22] text-[10px] font-semibold text-white">
            K
          </span>
          <span>Kompi Tools · Free WhatsApp link generator</span>
        </div>

        <div className="space-y-6 sm:space-y-7">
          <h1 className="text-3xl font-semibold tracking-tight text-[#020617] sm:text-4xl md:text-5xl">
            Free{" "}
            <span className="bg-[linear-gradient(120deg,#22c55e,#16a34a,#0f172a)] bg-clip-text text-transparent">
              WhatsApp link generator
            </span>{" "}
            to turn clicks into conversations.
          </h1>

          <p className="mx-auto max-w-3xl text-base leading-relaxed text-[#4b5563] sm:text-lg">
            Use Kompi&apos;s WhatsApp link generator to create click-to-chat
            links with pre-filled messages and tracking. Drop them into
            websites, bios, menus and QR codes so customers can start a
            WhatsApp chat in one tap or scan.
          </p>

          <p className="mx-auto max-w-xl text-xs leading-relaxed text-[#6b7280] sm:text-sm">
            Perfect for creators, small businesses, restaurants, events and
            support teams who want WhatsApp to feel like a natural part of
            their funnel — not a disconnected inbox.
          </p>

          <div className="mt-2 flex flex-wrap items-center justify-center gap-3">
            <a
              href="#whatsapp-link-tool"
              className="inline-flex items-center justify-center rounded-full bg-[#022c22] px-7 py-3 text-sm font-medium text-[#ecfdf5] shadow-md shadow-[#022c22]/30 transition hover:bg-black"
            >
              Generate WhatsApp link
            </a>
            <Link
              href="/signup"
              className="inline-flex items-center justify-center rounded-full border border-[#022c22] bg-[#f9fafb] px-7 py-3 text-sm font-medium text-[#022c22] shadow-sm hover:bg-[#ecfdf5]"
            >
              Save links in my Kompi workspace
            </Link>
          </div>

          <div className="mt-6 flex flex-wrap items-center justify-center gap-4 text-xs font-medium text-[#6b7280] sm:text-sm">
            <div className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-1 ring-1 ring-emerald-100">
              <span className="h-1.5 w-1.5 rounded-full bg-[#22c55e]" />
              <span>Works with WhatsApp & WhatsApp Business</span>
            </div>
            <span>• Pre-filled messages</span>
            <span>• UTM & click tracking with Kompi links</span>
          </div>
        </div>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  TOOL SECTION – render ContactLinkGenerator directly                      */
/* -------------------------------------------------------------------------- */

function WhatsappToolSection() {
  return (
    <section
      id="whatsapp-link-tool"
      className="px-4 pt-2 md:pt-4"
      aria-label="Kompi WhatsApp link generator tool"
    >
      <div className="mx-auto max-w-5xl space-y-4">
        <header className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
          <div className="space-y-1.5 text-left">
            <h2 className="text-lg font-semibold tracking-tight text-neutral-900 sm:text-xl">
              Try the Kompi WhatsApp link generator
            </h2>
            <p className="max-w-2xl text-xs text-neutral-600 sm:text-sm">
              Create click-to-chat links that open WhatsApp with the right
              number and pre-filled message. Wrap them in Kompi links or QR
              codes to plug straight into your existing funnels.
            </p>
          </div>
          <p className="text-xs text-neutral-500">
            Need QR codes too?{" "}
            <Link
              href="/qr-code-generator"
              className="font-medium text-neutral-900 underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
            >
              Open the QR code generator
            </Link>
            .
          </p>
        </header>

        <div className="rounded-[2rem] bg-white border border-neutral-200 shadow-sm p-3 sm:p-4 md:p-5">
          <ContactLinkGenerator />
        </div>

        <div className="grid gap-4 pt-1 text-xs text-neutral-600 sm:grid-cols-3 sm:text-sm">
          <div>
            <h3 className="font-semibold text-neutral-900">
              Turn links into QR codes
            </h3>
            <p>
              Paste your WhatsApp link into{" "}
              <Link
                href="/qr-code-generator"
                className="font-medium text-neutral-900 underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                Kompi QR Codes
              </Link>{" "}
              to create scannable WhatsApp contact QR codes for menus, flyers
              and packaging.
            </p>
          </div>
          <div>
            <h3 className="font-semibold text-neutral-900">
              Track conversations like campaigns
            </h3>
            <p>
              Combine your link with{" "}
              <Link
                href="/tools/utm-builder"
                className="font-medium text-neutral-900 underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                Kompi&apos;s UTM builder
              </Link>{" "}
              and{" "}
              <Link
                href="/links"
                className="font-medium text-neutral-900 underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                Kompi links
              </Link>{" "}
              to see which channels drive the most WhatsApp chats.
            </p>
          </div>
          <div>
            <h3 className="font-semibold text-neutral-900">
              Connect with your whole stack
            </h3>
            <p>
              Pair WhatsApp links with{" "}
              <Link
                href="/k-cards"
                className="font-medium text-neutral-900 underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                K-Cards
              </Link>{" "}
              and{" "}
              <Link
                href="/qr-menus"
                className="font-medium text-neutral-900 underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                QR menus
              </Link>{" "}
              so people can message you from profiles, menus and more.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  VIDEO SECTION                                                             */
/* -------------------------------------------------------------------------- */

function WhatsappVideoSection() {
  return (
    <section className="px-4 mt-12 md:mt-14">
      <div className="mx-auto max-w-5xl space-y-6 text-center">
        <div className="space-y-3">
          <h2 className="text-2xl font-semibold tracking-tight sm:text-3xl">
            Watch how Kompi&apos;s WhatsApp link generator works
          </h2>
          <p className="mx-auto max-w-2xl text-sm leading-relaxed text-[#4b5563] sm:text-base">
            See how to add your number, pre-fill a message, wrap it in a Kompi
            short link and turn it into a QR code — all in under a minute.
          </p>
        </div>

        <div className="mx-auto max-w-4xl rounded-[2rem] bg-white border border-neutral-200 shadow-sm p-3 sm:p-4 md:p-5">
          <div className="flex aspect-video w-full items-center justify-center overflow-hidden rounded-2xl bg-neutral-900/80">
            <video
              className="h-full w-full"
              src={SEO_VIDEO_SRC}
              controls
              preload="metadata"
              poster="/kompi-platform.png"
            >
              Sorry, your browser doesn&apos;t support embedded videos. You can
              watch it directly at <a href={SEO_VIDEO_SRC}>this link</a>.
            </video>
          </div>
        </div>

        <p className="text-xs text-neutral-600 sm:text-sm">
          Follow along with the live generator above and have your first
          WhatsApp link ready to go by the time the video ends.
        </p>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  LONG-FORM ARTICLE                                                         */
/* -------------------------------------------------------------------------- */

function WhatsappLongFormArticleSection() {
  return (
    <section
      className="px-4 mt-14 md:mt-16"
      aria-labelledby="whatsapp-link-guide-heading"
    >
      <div className="mx-auto max-w-5xl space-y-8 rounded-[2rem] border border-neutral-200 bg-white p-6 text-sm leading-relaxed text-neutral-800 shadow-sm md:p-8 lg:p-10 md:text-base">
        <header className="space-y-3">
          <h2
            id="whatsapp-link-guide-heading"
            className="text-2xl font-semibold tracking-tight md:text-3xl"
          >
            How to use a WhatsApp link generator to get more replies, not more
            friction
          </h2>
          <p>
            For a lot of small businesses, creators and teams,{" "}
            <strong>WhatsApp is where real conversations happen</strong>. It’s
            where bookings get confirmed, questions get answered and deals get
            nudged over the line. The problem? It&apos;s easy for WhatsApp to
            sit on the side of your funnel — a phone number on a menu or buried
            in a contact page — instead of being a smooth step that people can
            tap or scan.
          </p>
          <p>
            A <strong>WhatsApp link generator</strong> fixes that. Instead of
            asking people to manually add your number, you give them a simple
            link or QR code that does the work for them. It opens WhatsApp with
            your number selected and — if you want — a pre-filled message
            waiting to send.
          </p>
        </header>

        <section className="space-y-3">
          <h3 className="text-xl font-semibold md:text-2xl">
            What a WhatsApp link actually is (and why it matters)
          </h3>
          <p>
            Under the hood, a WhatsApp link is just a normal URL using the
            <code className="mx-1 rounded bg-neutral-100 px-1 py-0.5 text-[0.8em]">
              wa.me
            </code>{" "}
            or{" "}
            <code className="mx-1 rounded bg-neutral-100 px-1 py-0.5 text-[0.8em]">
              api.whatsapp.com
            </code>{" "}
            formats. When someone taps it, WhatsApp checks whether the app is
            installed and then opens a chat with your number.
          </p>
          <p>
            You can paste that URL anywhere a normal link would go — a button
            on your website, an Instagram bio, a call-to-action in an email, a
            QR code on a receipt, menu or poster. Kompi&apos;s{" "}
            <strong>WhatsApp link generator</strong> simply makes it easy to
            construct that URL, encode your message correctly and optionally
            layer on tracking with Kompi links and UTMs.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-xl font-semibold md:text-2xl">
            Where WhatsApp links shine in 2025
          </h3>
          <p>
            WhatsApp links are most powerful anywhere you want a{" "}
            <strong>direct, human conversation</strong> instead of a generic
            form or slow inbox:
          </p>
          <ul className="list-disc list-inside space-y-2">
            <li>
              <strong>Restaurants & cafés:</strong> Add a WhatsApp link to your{" "}
              <Link
                href="/qr-menus"
                className="underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                QR menu
              </Link>{" "}
              so customers can ask questions or place orders.
            </li>
            <li>
              <strong>Creators & coaches:</strong> Use a WhatsApp link on your{" "}
              <Link
                href="/k-cards"
                className="underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                K-Card
              </Link>{" "}
              link-in-bio page for discovery calls or client support.
            </li>
            <li>
              <strong>Local services:</strong> Turn “call us” buttons into
              “Chat on WhatsApp” so people can reach you without a phone call.
            </li>
            <li>
              <strong>Events:</strong> Put WhatsApp QR codes on tickets and
              signage so attendees can message your team if they get stuck.
            </li>
            <li>
              <strong>Customer support:</strong> Add WhatsApp links to emails
              and receipts to give people a fast way to ask follow-up questions.
            </li>
          </ul>
          <p>
            These are all tiny changes, but they make it much more natural for
            people to reach you where they already spend time — instead of
            getting bounced between channels.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-xl font-semibold md:text-2xl">
            Building a high-converting WhatsApp link step by step
          </h3>
          <p>
            With Kompi, you don&apos;t need to memorize URL syntax. The{" "}
            <strong>WhatsApp link generator</strong> walks you through a simple
            flow:
          </p>
          <ol className="list-decimal list-inside space-y-2">
            <li>
              <strong>Add your full phone number</strong> with country code and
              no special characters.
            </li>
            <li>
              <strong>Write a pre-filled message</strong> that reflects what
              you want people to say by default — “I’d like to book a table,”
              “I’m interested in your package A,” or “I have a question about
              my order.”
            </li>
            <li>
              <strong>Choose your link style</strong>: keep the raw WhatsApp
              URL or wrap it in a branded Kompi short link that’s easier to
              share and remember.
            </li>
            <li>
              <strong>Add UTM parameters</strong> with the{" "}
              <Link
                href="/tools/utm-builder"
                className="underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                UTM builder
              </Link>{" "}
              so you can attribute conversations back to specific ads, bios or
              pages.
            </li>
            <li>
              <strong>Turn the link into a QR code</strong> using the{" "}
              <Link
                href="/qr-code-generator"
                className="underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                QR code generator
              </Link>{" "}
              if you want it on menus, posters or packaging.
            </li>
          </ol>
          <p>
            You end up with a short, clean link or QR code that fits wherever
            you need it — from your{" "}
            <Link
              href="/links"
              className="underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
            >
              Kompi links
            </Link>{" "}
            page to printed assets.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-xl font-semibold md:text-2xl">
            Writing pre-filled messages that actually get replies
          </h3>
          <p>
            Pre-filled messages save people time, but they also set the tone
            for the whole conversation. A vague “Hi” doesn’t help anyone. A
            clear, friendly prompt does.
          </p>
          <p>Some ideas that work well in practice:</p>
          <ul className="list-disc list-inside space-y-2">
            <li>
              Include the{" "}
              <strong>context of where the person came from</strong> — e.g.
              “Hi, I’m on your website and I’d like to book a table for…”
            </li>
            <li>
              Ask for the <strong>minimum details you need</strong> to help
              them (time, date, package type, order number).
            </li>
            <li>
              Keep the tone <strong>on-brand but simple</strong>. Your team
              will finish the conversation; the message just gets it started.
            </li>
          </ul>
          <p>
            Kompi doesn’t lock you into any template — you can edit and test
            different pre-fill messages to see what gets the fastest and most
            helpful replies on both sides.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-xl font-semibold md:text-2xl">
            Tracking WhatsApp as a proper channel, not a black box
          </h3>
          <p>
            The moment you start using WhatsApp links seriously, you&apos;ll
            want to know a simple thing:{" "}
            <strong>which campaigns are actually driving chats?</strong>
          </p>
          <p>
            Kompi makes that possible by treating WhatsApp like any other link
            destination. You can:
          </p>
          <ul className="list-disc list-inside space-y-2">
            <li>
              Wrap your WhatsApp URL with a{" "}
              <Link
                href="/links"
                className="underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                Kompi short link
              </Link>{" "}
              so every click is counted.
            </li>
            <li>
              Use the{" "}
              <Link
                href="/tools/utm-builder"
                className="underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                UTM builder
              </Link>{" "}
              to pass source/medium/campaign data into your analytics tools.
            </li>
            <li>
              Turn that short link into a QR code, then track which physical
              placements generate the most scans and chats.
            </li>
          </ul>
          <p>
            That way, when you look at your analytics, WhatsApp isn&apos;t just
            “somewhere people message us.” It becomes a measurable part of your
            growth stack, right alongside landing pages and email.
          </p>
        </section>

        <section className="space-y-3">
          <h3 className="text-xl font-semibold md:text-2xl">
            Pairing WhatsApp with QR codes, menus and link-in-bio pages
          </h3>
          <p>
            The smartest teams don’t treat WhatsApp links as standalone
            buttons. They see them as building blocks that fit into multiple
            Kompi surfaces:
          </p>
          <ul className="list-disc list-inside space-y-2">
            <li>
              Add a WhatsApp button to your{" "}
              <Link
                href="/k-cards"
                className="underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                K-Card
              </Link>{" "}
              so fans and clients can DM you straight from your social bios.
            </li>
            <li>
              Place a WhatsApp QR code next to contact sections on{" "}
              <Link
                href="/qr-menus"
                className="underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                QR menus
              </Link>{" "}
              for bookings, delivery requests or special events.
            </li>
            <li>
              Combine WhatsApp links with dynamic QR codes from{" "}
              <Link
                href="/kr-codes"
                className="underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                Kompi KR Codes
              </Link>{" "}
              so you can update destinations later without reprinting.
            </li>
          </ul>
          <p>
            Everything still lives in the same workspace, so your team doesn’t
            have to jump between tools whenever they want to tweak a funnel or
            update a number.
          </p>
        </section>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  USE CASES SECTION                                                         */
/* -------------------------------------------------------------------------- */

function WhatsappUseCasesSection() {
  return (
    <section className="mt-16 border-t border-neutral-200 bg-[#f9fafb] md:mt-20">
      <div className="mx-auto max-w-5xl space-y-10 px-4 py-12 md:py-16">
        <header className="mx-auto max-w-3xl space-y-3 text-center">
          <h2 className="text-xs font-semibold uppercase tracking-[0.3em] text-[#022c22] sm:text-sm">
            WHERE WHATSAPP LINKS FIT
          </h2>
          <p className="text-2xl font-semibold tracking-tight md:text-3xl">
            One WhatsApp link generator, three very normal use cases.
          </p>
          <p className="text-sm text-[#4b5563] md:text-base">
            Kompi&apos;s WhatsApp link generator works anywhere you want people
            to start a chat instead of filling out another form — from menus and
            posters to profiles and ads.
          </p>
        </header>

        <div className="grid gap-6 md:grid-cols-3">
          <div className="flex flex-col justify-between rounded-3xl bg-white p-6 ring-1 ring-emerald-100">
            <div className="space-y-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-[#16a34a]">
                RESTAURANTS & LOCAL
              </p>
              <h3 className="text-lg font-semibold text-[#022c22] md:text-xl">
                Bookings & quick questions
              </h3>
              <p className="text-sm text-[#4b5563]">
                Put “Chat on WhatsApp” links on{" "}
                <Link
                  href="/qr-menus"
                  className="underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
                >
                  QR menus
                </Link>{" "}
                and websites so people can confirm reservations or ask about
                availability without calling.
              </p>
              <ul className="mt-2 space-y-1.5 text-sm text-[#065f46]">
                <li>• Pre-filled booking requests</li>
                <li>• QR codes on tables & windows</li>
                <li>• Faster replies than email forms</li>
              </ul>
            </div>
          </div>

          <div className="flex flex-col justify-between rounded-3xl bg-[#ecfdf5] p-6 ring-2 ring-[#22c55e]">
            <div className="space-y-3">
              <div className="inline-flex items-center gap-2 rounded-full bg-[#022c22] px-3 py-1 text-[11px] font-semibold text-[#ecfdf5]">
                <span className="h-1.5 w-1.5 rounded-full bg-[#22c55e]" />
                Recommended
              </div>
              <h3 className="text-lg font-semibold text-[#022c22] md:text-xl">
                Creators, coaches & sales
              </h3>
              <p className="text-sm text-[#022c22]">
                Send qualified leads straight into WhatsApp from link-in-bio
                pages, funnels and ads so you can close deals in a real
                conversation.
              </p>
              <ul className="mt-2 space-y-1.5 text-sm text-[#022c22]">
                <li>• Add to K-Cards link-in-bio</li>
                <li>• Different links per campaign</li>
                <li>• UTM tracking with Kompi links</li>
              </ul>
            </div>
          </div>

          <div className="flex flex-col justify-between rounded-3xl bg-white p-6 ring-1 ring-neutral-200">
            <div className="space-y-3">
              <p className="text-xs font-semibold uppercase tracking-wide text-[#0f172a]">
                SUPPORT & OPERATIONS
              </p>
              <h3 className="text-lg font-semibold text-[#0f172a] md:text-xl">
                Customer support & follow-ups
              </h3>
              <p className="text-sm text-[#4b5563]">
                Add WhatsApp links to receipts, shipping emails or packaging so
                people can reach your team with contextual questions.
              </p>
              <ul className="mt-2 space-y-1.5 text-sm text-[#111827]">
                <li>• Links in order emails</li>
                <li>• QR codes on boxes & inserts</li>
                <li>• Pre-filled “I need help with…” messages</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  WHY KOMPI SECTION                                                         */
/* -------------------------------------------------------------------------- */

function WhatsappWhyKompiSection() {
  return (
    <section className="border-t border-neutral-200 bg-[#f7f7f4]">
      <div className="mx-auto max-w-5xl space-y-8 px-4 py-12 md:py-16">
        <header className="space-y-3 text-center">
          <h2 className="text-2xl font-semibold tracking-tight md:text-3xl">
            Why use Kompi for WhatsApp link generation?
          </h2>
          <p className="mx-auto max-w-2xl text-sm text-neutral-700 md:text-base">
            Kompi doesn&apos;t just spit out a single URL — it connects your
            WhatsApp links with QR codes, link tracking, menus and link-in-bio
            pages so the whole flow makes sense.
          </p>
        </header>

        <div className="grid gap-4 md:grid-cols-3">
          <div className="space-y-2 rounded-2xl border border-neutral-200 bg-white p-5">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">
              BUILT FOR GROWTH
            </p>
            <h3 className="text-sm font-semibold text-neutral-900">
              Links that plug into your stack
            </h3>
            <p className="text-xs text-neutral-600 md:text-sm">
              Use WhatsApp links alongside QR codes,{" "}
              <Link
                href="/links"
                className="underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-700"
              >
                short links
              </Link>{" "}
              and K-Cards instead of juggling separate tools for each piece.
            </p>
          </div>

          <div className="space-y-2 rounded-2xl border border-emerald-200 bg-white p-5">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">
              BUILT FOR CLARITY
            </p>
            <h3 className="text-sm font-semibold text-neutral-900">
              Tracking that makes sense
            </h3>
            <p className="text-xs text-neutral-600 md:text-sm">
              Pair the WhatsApp link generator with Kompi&apos;s UTM Builder and
              analytics so you know which buttons, bios and QR codes actually
              started conversations.
            </p>
          </div>

          <div className="space-y-2 rounded-2xl border border-neutral-200 bg-white p-5">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-sky-700">
              BUILT TO SCALE
            </p>
            <h3 className="text-sm font-semibold text-neutral-900">
              From solo to team-wide
            </h3>
            <p className="text-xs text-neutral-600 md:text-sm">
              Start free, then add teammates and clients into shared workspaces
              when you&apos;re ready. Keep WhatsApp links organised by brand,
              product or campaign.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  COMPARISON SECTION                                                        */
/* -------------------------------------------------------------------------- */

function WhatsappComparisonSection() {
  return (
    <section className="border-t border-neutral-200 bg-[#f9fafb]">
      <div className="mx-auto max-w-5xl space-y-6 px-4 py-12 md:py-16">
        <header className="max-w-3xl space-y-3">
          <h2 className="text-2xl font-semibold tracking-tight md:text-3xl">
            Kompi WhatsApp link generator vs copy-paste hacks
          </h2>
          <p className="text-sm text-neutral-700 md:text-base">
            You can build WhatsApp links manually, but it&apos;s easy to make
            mistakes with encoding, tracking and number formatting. Kompi
            handles the details and connects everything to your wider toolkit.
          </p>
        </header>

        <div className="overflow-x-auto">
          <table className="w-full border-collapse text-left text-xs md:text-sm">
            <thead>
              <tr className="border-b border-neutral-300 bg-white">
                <th className="py-3 pr-4 font-semibold">Feature</th>
                <th className="px-4 py-3 font-semibold">
                  Kompi WhatsApp link generator
                </th>
                <th className="px-4 py-3 font-semibold">
                  Manual / ad-hoc setup
                </th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-neutral-200">
                <td className="py-3 pr-4">Message encoding</td>
                <td className="px-4 py-3">
                  Automatically URL-encodes spaces, emojis and punctuation.
                </td>
                <td className="px-4 py-3">
                  Easy to break links with unencoded characters or line breaks.
                </td>
              </tr>
              <tr className="border-b border-neutral-200">
                <td className="py-3 pr-4">Tracking & UTMs</td>
                <td className="px-4 py-3">
                  Built-in support via Kompi links and UTM builder.
                </td>
                <td className="px-4 py-3">
                  Requires manual string editing and separate tools.
                </td>
              </tr>
              <tr className="border-b border-neutral-200">
                <td className="py-3 pr-4">QR code support</td>
                <td className="px-4 py-3">
                  Paste links directly into the{" "}
                  <Link
                    href="/qr-code-generator"
                    className="underline underline-offset-2 decoration-neutral-300 hover:decoration-neutral-700"
                  >
                    QR code generator
                  </Link>{" "}
                  for instant WhatsApp QR codes.
                </td>
                <td className="px-4 py-3">
                  Requires another generator, often with no tracking.
                </td>
              </tr>
              <tr className="border-b border-neutral-200">
                <td className="py-3 pr-4">Organisation</td>
                <td className="px-4 py-3">
                  Links live inside workspaces alongside other Kompi tools.
                </td>
                <td className="px-4 py-3">
                  Links live in random docs, chats or design files.
                </td>
              </tr>
              <tr>
                <td className="py-3 pr-4">Workflow fit</td>
                <td className="px-4 py-3">
                  Built for creators, brands and teams using WhatsApp seriously.
                </td>
                <td className="px-4 py-3">
                  Fine for one-off experiments, messy at any kind of scale.
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <p className="text-xs text-neutral-600 md:text-sm">
          With Kompi, you spend less time fixing broken links and more time
          having the conversations those links were meant to start.
        </p>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  FAQ / TRUST / RELATED LINKS                                               */
/* -------------------------------------------------------------------------- */

function WhatsappFaqSection() {
  return (
    <section className="border-t border-neutral-200 bg-[#f7f7f4]">
      <div className="mx-auto max-w-4xl px-4 py-12 md:py-16">
        <header className="mb-6 space-y-3">
          <h2 className="text-2xl font-semibold tracking-tight md:text-3xl">
            WhatsApp link generator FAQs
          </h2>
          <p className="text-sm text-neutral-700 md:text-base">
            Everything you need to know about using Kompi as your WhatsApp link
            generator, from formatting numbers to tracking campaigns.
          </p>
        </header>

        <div className="space-y-4">
          {faqs.map((faq) => (
            <details
              key={faq.question}
              className="group rounded-2xl border border-neutral-200 bg-white p-4 md:p-5"
            >
              <summary className="flex cursor-pointer list-none items-center justify-between gap-2">
                <span className="text-sm font-medium md:text-base">
                  {faq.question}
                </span>
                <span className="hidden text-xs text-neutral-500 group-open:inline">
                  −
                </span>
                <span className="inline text-xs text-neutral-500 group-open:hidden">
                  +
                </span>
              </summary>
              <p className="mt-3 text-xs text-neutral-700 md:text-sm">
                {faq.answer}
              </p>
            </details>
          ))}
        </div>
      </div>
    </section>
  );
}

function WhatsappTrustSection() {
  return (
    <section className="border-t border-neutral-200 bg-white">
      <div className="mx-auto max-w-4xl space-y-4 px-4 py-10 text-xs text-neutral-700 md:py-12 md:text-sm">
        <h2 className="text-base font-semibold tracking-tight md:text-lg">
          Privacy, consent and responsible WhatsApp use
        </h2>
        <p>
          Kompi&apos;s WhatsApp link generator helps you create links and QR
          codes that make it easy for people to message you. As always, how you
          use those links matters. Only share WhatsApp links in places where
          people would reasonably expect to contact you, and avoid adding
          numbers to group chats or broadcast lists without consent.
        </p>
        <p>
          Because WhatsApp conversations happen outside Kompi, we don&apos;t
          see or store your message content. When you use Kompi links and UTMs,
          we track clicks and scans — not the chat itself — so you can measure
          performance while still respecting privacy.
        </p>
        <p>
          For public campaigns, consider pairing WhatsApp with other channels
          like email and QR menus so people can choose the contact method that
          feels right for them.
        </p>
      </div>
    </section>
  );
}

function WhatsappRelatedLinksSection() {
  return (
    <section className="border-t border-neutral-200 bg-[#f9fafb]">
      <div className="mx-auto max-w-4xl space-y-4 px-4 py-10 md:py-12">
        <h2 className="text-base font-semibold tracking-tight md:text-lg">
          Related Kompi tools & pages
        </h2>
        <p className="text-xs text-neutral-700 md:text-sm">
          Build a full WhatsApp-powered funnel using these Kompi tools:
        </p>
        <ul className="grid gap-3 text-xs md:grid-cols-2 md:text-sm">
          <li>
            <Link
              href="/links"
              className="inline-flex w-full items-center justify-between rounded-2xl border border-neutral-200 bg-white px-4 py-3 transition-colors hover:border-neutral-400"
            >
              <span>Kompi Links – branded short links</span>
              <span>↗</span>
            </Link>
          </li>
          <li>
            <Link
              href="/tools/utm-builder"
              className="inline-flex w-full items-center justify-between rounded-2xl border border-neutral-200 bg-white px-4 py-3 transition-colors hover:border-neutral-400"
            >
              <span>UTM Builder – campaign tracking</span>
              <span>↗</span>
            </Link>
          </li>
          <li>
            <Link
              href="/qr-code-generator"
              className="inline-flex w-full items-center justify-between rounded-2xl border border-neutral-200 bg-white px-4 py-3 transition-colors hover:border-neutral-400"
            >
              <span>QR code generator for WhatsApp links</span>
              <span>↗</span>
            </Link>
          </li>
          <li>
            <Link
              href="/k-cards"
              className="inline-flex w-full items-center justify-between rounded-2xl border border-neutral-200 bg-white px-4 py-3 transition-colors hover:border-neutral-400"
            >
              <span>K-Cards – link-in-bio with WhatsApp</span>
              <span>↗</span>
            </Link>
          </li>
        </ul>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  JSON-LD SCHEMAS                                                           */
/* -------------------------------------------------------------------------- */

function getWebAppSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: "Kompi WhatsApp Link Generator",
    applicationCategory: "UtilityApplication",
    description:
      "Free online WhatsApp link generator by Kompi. Create click-to-chat links with pre-filled messages, UTM tracking and QR codes for your website, social bios and campaigns.",
    operatingSystem: "Any",
    url: `${DOMAIN}/whatsapp-link-generator`,
  };
}

function getFaqSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer,
      },
    })),
  };
}

function getHowToSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: "How to create a WhatsApp link with Kompi",
    description:
      "Step-by-step instructions for generating a WhatsApp click-to-chat link using Kompi's free WhatsApp link generator.",
    step: howToSteps.map((step) => ({
      "@type": "HowToStep",
      position: step.position,
      name: step.name,
      text: step.text,
    })),
  };
}

function getVideoSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: "How to use the Kompi WhatsApp link generator",
    description:
      "Quick walkthrough of creating WhatsApp click-to-chat links, adding tracking and turning them into QR codes with Kompi.",
    thumbnailUrl: [SEO_THUMBNAIL_ABS],
    uploadDate: "2025-01-01",
    contentUrl: SEO_VIDEO_ABS,
    embedUrl: SEO_VIDEO_ABS,
  };
}

/* -------------------------------------------------------------------------- */
/*  PAGE COMPONENT                                                            */
/* -------------------------------------------------------------------------- */

export default function WhatsappLinkGeneratorSeoPage() {
  const webAppSchema = getWebAppSchema();
  const faqSchema = getFaqSchema();
  const howToSchema = getHowToSchema();
  const videoSchema = getVideoSchema();

  const jsonLd = [webAppSchema, faqSchema, howToSchema, videoSchema];

  return (
    <>
      <Script
        id="whatsapp-link-generator-jsonld"
        type="application/ld+json"
        strategy="afterInteractive"
      >
        {JSON.stringify(jsonLd)}
      </Script>

      <div className="min-h-screen bg-[#f3f4f6] text-[#020617]">
        <Navbar />
        <main className="space-y-16 pb-20 pt-16 md:space-y-20 md:pt-20">
          <section className="px-4">
            <div className="mx-auto max-w-5xl">
              <WhatsappHeroSection />
            </div>
          </section>

          <WhatsappToolSection />
          <WhatsappVideoSection />
          <WhatsappLongFormArticleSection />
          <WhatsappUseCasesSection />
          <WhatsappWhyKompiSection />
          <WhatsappComparisonSection />
          <WhatsappFaqSection />
          <WhatsappTrustSection />
          <WhatsappRelatedLinksSection />
        </main>
        <FooterCTA />
      </div>
    </>
  );
}
